package halogen.cache.room.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

@Database(entities = [ThemeEntity::class], version = 1)
@ConstructedBy(HalogenDatabaseConstructor::class)
internal abstract class HalogenDatabase : RoomDatabase() {
    abstract fun themeDao(): ThemeDao
}

/**
 * Room KMP database constructor.
 *
 * The `actual` implementations are generated by Room's KSP processor
 * for each target (Android, JVM, iOS). The `@Suppress("NO_ACTUAL_FOR_EXPECT")`
 * is required because the actuals are code-generated, not hand-written.
 * The `initialize()` override must be declared here so that the intermediate
 * `roomMain` source set's metadata compilation can type-check the interface
 * contract before KSP runs.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
internal expect object HalogenDatabaseConstructor : RoomDatabaseConstructor<HalogenDatabase> {
    override fun initialize(): HalogenDatabase
}
