package halogen.engine

import halogen.HalogenThemeSpec

/**
 * Sealed hierarchy representing the outcome of a theme resolution attempt.
 *
 * Use [themeSpec] for a convenient nullable accessor and [isSuccess] to check
 * whether a usable theme was obtained regardless of source.
 */
public sealed class HalogenResult {
    /** A fresh theme was generated by an LLM provider. */
    public data class Success(val spec: HalogenThemeSpec) : HalogenResult()

    /** The theme was served from the local cache. */
    public data class Cached(val spec: HalogenThemeSpec) : HalogenResult()

    /** The theme was fetched from a [HalogenServerProvider]. */
    public data class FromServer(val spec: HalogenThemeSpec) : HalogenResult()

    /** The LLM returned output that could not be parsed into a valid [HalogenThemeSpec]. */
    public data class ParseError(val message: String, val rawResponse: String? = null) : HalogenResult()

    /** No provider was available to generate a theme. */
    public data object Unavailable : HalogenResult()

    /** The provider reported a quota or rate-limit error. */
    public data object QuotaExceeded : HalogenResult()

    /** The [HalogenThemeSpec] if resolution succeeded, or `null` otherwise. */
    public val themeSpec: HalogenThemeSpec?
        get() = when (this) {
            is Success -> spec
            is Cached -> spec
            is FromServer -> spec
            else -> null
        }

    /** `true` when a usable [HalogenThemeSpec] was obtained. */
    public val isSuccess: Boolean get() = themeSpec != null
}
