package halogen.engine

/**
 * Describes how a cached [halogen.HalogenThemeSpec] was originally obtained.
 */
public enum class ThemeSource {
    /** Generated by an on-device or cloud LLM provider. */
    LLM,
    /** Fetched from a [HalogenRemoteThemes] source. */
    SERVER,
    /** Supplied directly by application code via [HalogenEngine.apply]. */
    MANUAL,
}
